version: '3'

services:
  otrs:
    image: juanluisbaptiste/otrs:latest
    ports:
      - '80:80'
    # If running behind a proxy container, expose the ports instead
    # and link the proxy container to this one.
    #  expose:
    #  - "80"
    depends_on:
      - mariadb
      # Uncomment if using the smtp relay
      # - postfix
    env_file: .env
    volumes:
      - './volumes/config:/opt/otrs/Kernel'
      # Uncomment if using OTRS_ARTICLE_STORAGE_TYPE=ArticleStorageFS
      #- ./volumes/article:/opt/otrs/var/article
      - ./volumes/skins:/opt/otrs/var/httpd/htdocs/skins/
      - ./backups:/var/otrs/backups
      - ./volumes/otrs:/opt/otrs/
      - /etc/localtime:/etc/localtime:ro
  mariadb:
    image: juanluisbaptiste/otrs-mariadb:latest
    expose:
      - "3306"
    env_file: .env
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
